version: '3.6'
services:
  registration-mongo:
    container_name: registration-mongo
    image: mongo
    restart: always
    volumes:
      - registration_mongodb_vol:/data/db
    ports:
      - $GLS_MONGO_EXTERNAL_HOST:$GLS_MONGO_EXTERNAL_PORT:27017
    networks:
      - services-tier

  registration-node:
    container_name: registration-node
    restart: always
    depends_on:
      - registration-mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_SMS_GATE_HOST:$GLS_SMS_GATE_PORT:$GLS_SMS_GATE_PORT
    env_file:
      - .env

volumes:
  registration-mongo:

networks:
  services-tier:
