// Описание переменных окружения смотри в Readme.
const env = process.env;

module.exports = {
    GLS_SMS_VERIFY_EXPIRATION_HOURS: env.GLS_SMS_VERIFY_EXPIRATION_HOURS || 1,
    GLS_GOOGLE_CAPTCHA_SECRET: env.GLS_GOOGLE_CAPTCHA_SECRET,
    GLS_SMS_RESEND_CODE_TIMEOUT: 1000 * 45,
    GLS_REGISTRAR_KEY: env.GLS_REGISTRAR_KEY,
    GLS_REGISTRAR_ACCOUNT: env.GLS_REGISTRAR_ACCOUNT,
    GLS_ACCOUNT_DELEGATION_FEE: env.GLS_ACCOUNT_DELEGATION_FEE || 2.7,
    GLS_SMS_GATE_HOST: env.GLS_SMS_GATE_HOST || '0.0.0.0',
    GLS_SMS_GATE_PORT: env.GLS_SMS_GATE_PORT || 8090,
    GLS_SMS_GATE_LOGIN: env.GLS_SMS_GATE_LOGIN,
    GLS_SMS_GATE_PASS: env.GLS_SMS_GATE_PASS,
    GLS_SMS_GATE_SECRET_SID: env.GLS_SMS_GATE_SECRET_SID,
    GLS_TWILIO_SECRET: env.GLS_TWILIO_SECRET,
    GLS_TWILIO_PHONE_FROM: env.GLS_TWILIO_PHONE_FROM,
};
