// Описание переменных окружения смотри в Readme.
const env = process.env;

module.exports = {
    GLS_PHONE_VERIFY_TIMEOUT: env.GLS_PHONE_VERIFY_TIMEOUT,
    GLS_SMS_VERIFY_EXPIRATION_HOURS: env.GLS_SMS_VERIFY_EXPIRATION_HOURS || 1,
    GLS_GOOGLE_CAPTCHA_SECRET: env.GLS_GOOGLE_CAPTCHA_SECRET,
    GLS_SMS_RESEND_CODE_TIMEOUT: 1000 * 45,
    GLS_REGISTRAR_KEY: env.GLS_REGISTRAR_KEY,
    GLS_REGISTRAR_ACCOUNT: env.GLS_REGISTRAR_ACCOUNT,
    GLS_ACCOUNT_DELEGATION_FEE: env.GLS_ACCOUNT_DELEGATION_FEE,
    GLS_SMS_GATE_HOST: env.GLS_SMS_GATE_HOST,
    GLS_SMS_GATE_PORT: env.GLS_SMS_GATE_PORT,
    GLS_SMS_GATE_LOGIN: env.GLS_SMS_GATE_LOGIN,
    GLS_SMS_GATE_PASS: env.GLS_SMS_GATE_PASS,
    GLS_SMS_GATE_SECRET_SID: env.GLS_SMS_GATE_SECRET_SID,
};
